# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sKey', models.CharField(max_length=40, verbose_name='Secret Key')),
                ('iKey', models.CharField(max_length=20, unique=True, verbose_name='Integration Key')),
                ('name', models.CharField(max_length=30)),
                ('app_type', models.CharField(max_length=30)),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether the application create by admin', verbose_name='admin status')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifer', models.CharField(max_length=20)),
                ('is_activated', models.BooleanField(default=False)),
                ('dKey', models.CharField(max_length=256, null=True, verbose_name='Device Key')),
                ('device_name', models.CharField(max_length=30, null=True)),
                ('device_model', models.CharField(max_length=20, null=True)),
                ('platform', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gKey', models.CharField(max_length=20, unique=True, verbose_name='Group Key')),
                ('group_name', models.CharField(max_length=30)),
                ('group_description', models.EmailField(blank=True, default=' ', max_length=100)),
                ('group_status', models.CharField(default='Active', help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uKey', models.CharField(max_length=20, unique=True, verbose_name='User Key')),
                ('user_name', models.CharField(max_length=30)),
                ('user_real_name', models.CharField(blank=True, max_length=30)),
                ('user_phone', models.CharField(blank=True, max_length=11)),
                ('user_email', models.EmailField(blank=True, max_length=30)),
                ('user_status', models.CharField(default='Active', help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', max_length=10)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
        ),
    ]
