# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170713_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='seed',
            field=models.CharField(max_length=16, null=True, verbose_name='Random Seed'),
        ),
    ]
